<?php if (!defined('ACCESS')) die('DIRECT ACCESS NOT ALLOWED'); ?>

<?php

    $results = $DB->query("SELECT * FROM users WHERE id=".$_SESSION[AUTH_ID]);
    $users = mysqli_fetch_all($results, MYSQLI_ASSOC);

    $select = $DB->query("SELECT * FROM approvedtable
    INNER JOIN categorytable ON approvedtable.cat_id = categorytable.cat_id
    INNER JOIN users ON approvedtable.userID = users.id
    INNER JOIN departmenttable ON users.dept_id = departmenttable.dept_id");

    // create PDF document instance
    require('vendor/setasign/fpdf/fpdf.php');
    

    $pdf = new FPDF('L', 'mm', 'Legal');
    // add new page to document
    $pdf->AddPage();
    
    $pdf->SetFont('Arial', 'B', 20);
    $pdf->Cell(0, 20, 'Purchase Request', 0, 1, 'C');
    

    $pdf->SetFont('Arial','',14);
    $pdf->Cell(235, 20, ucwords('entity name:   '. strtoupper('central philippines state university')), 0, 0);
    $pdf->Cell(100, 20, ucwords('fund cluster:'), 0, 1);

    $view = $select->fetch_object();
    $pdf->Cell(50, 15, 'Office/Section', 1, 0);
    $pdf->Cell(150, 15, ucwords($view->department), 1, 0);

    $date = $view->created_at;
    $formatted_date = date('M, d, Y', strtotime($date));
    $pdf->Cell(60, 15, 'PR No.'. $view->request_id. 'Responsibility Center Code:', 1, 0);
    $pdf->Cell(75, 15, 'Date: '.$formatted_date, 1, 1);

    // define font size and style
    $pdf->Cell(50, 10, strtoupper('stock no.'), 1, 0);
    $pdf->Cell(40, 10, strtoupper('unit'), 1, 0);
    $pdf->Cell(110, 10, strtoupper('item description'), 1, 0);
    $pdf->Cell(25, 10, strtoupper('qty.'), 1, 0);
    $pdf->Cell(35, 10, strtoupper('unit cost'), 1, 0);
    $pdf->Cell(75, 10, strtoupper('total cost'), 1, 1);

    // Retrieve the filtered data from the session
    $filtered_data = $_SESSION['filtered_data'];

    $total_cost = 0;
    foreach($filtered_data as $row){
    $total_cost += $row['total_cost'];
    $pdf->Cell(50, 10, '', 1, 0);
    $pdf->Cell(40, 10, ucwords($row['unit']), 1, 0);
    $pdf->Cell(110, 10, ucwords($row['category']), 1, 0);
    $pdf->Cell(25, 10, $row['quantity'], 1, 0);
    $pdf->Cell(35, 10, $row['cost'], 1, 0);
    $pdf->Cell(75, 10, $row['total_cost'], 1, 1);
    }    

    // bottom total
    $pdf->Cell(260, 10, 'Total', 1, 0);
    $pdf->Cell(75, 10, $total_cost, 1, 1);

    // $pdf->SetFont('Arial','',11);
    // $pdf->Cell(190, 10, ucwords($row['purpose']), 0, 1);

    $select = $DB->query("SELECT * FROM invoice");
    $designation = $select->fetch_object();
    $pdf->SetFont('Arial','B',14);
    $pdf->Cell(50, 10, '', 0, 0);
    $pdf->Cell(150, 10, 'Requested by:', 0, 0);
    $pdf->Cell(135, 10, 'Approved by:', 0, 1);

    $pdf->Cell(335, 10, '', 0, 1);

    $pdf->Cell(50, 10, '', 0, 0);
    $pdf->Cell(150, 10, strtoupper($designation->requestedfullname), 0, 0, 'C');
    $pdf->Cell(135, 10, strtoupper($designation->approvedfullname), 0, 1, 'C');

    $pdf->SetFont('Arial','',14);
    $pdf->Cell(50, 10, '', 0, 0);
    $pdf->Cell(150, 5, strtoupper($designation->requesteddesignation), 0, 0, 'C');
    $pdf->Cell(135, 5, strtoupper($designation->approveddesignation), 0, 1, 'C');

    // set font and size for footer
    $pdf->SetFont('Arial', '', 7);

    // define footer content
    $footer = 'Generated by Central Philippines State University Procurement Office App';

    // add footer to every page
    $pdf->AliasNbPages();
    $pdf->SetY(-32);
    $pdf->Cell(0, 10, strtoupper($footer), 0, 1,);

    $pdf->Output();
