<?php
require('vendor/setasign/fpdf/fpdf.php');

class PDF extends FPDF
{
    // Page header
    function Header()
    {
        // Logo image
        // ('image path, left, top, width, height)
        $this->Image('./assets/images/logo.png', 50, 7, 15, 15);

        // Arial bold 15
        $this->SetFont('Arial', 'B', 12);

        // Move to the right
        $this->Cell(80);

        // Title
        $this->Cell(35, 5, ucwords('central philippines state university'), 0, 1, 'C');

        // Set font for subtitle
        $this->SetFont('Arial', '', 7);

        // Set subtitle
        $this->Cell(0, 5, ucwords('kabankalan, negros occidental, philippines (6111)'), 0, 1, 'C');

        // Line break
        $this->Ln(10);
    }

    // Page footer
    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY(-20);

        // define footer content
        $footer = 'Generated by Central Philippines State University Procurement Office App';
        // set font and size for footer
        $this->SetFont('Arial', 'I', 7);
        $this->Cell(0, 10, strtoupper($footer), 0, 0);

        // Page number
        $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 1, 'R');
    }

}

$pdf = new PDF();

        // Set document properties
        $pdf->SetTitle('CPSU | Procurement Office');
        $pdf->SetAuthor('BIST 4D');
        $pdf->SetCreator('FPDF');

        // Set font
        $pdf->SetFont('Arial', '', 11);

        // Add content to the PDF
        $pdf->AddPage('P', 'LEGAL');


                // Database Calling
                $results = $DB->query("SELECT * FROM users WHERE id=" . $_SESSION[AUTH_ID]);
                $users = mysqli_fetch_all($results, MYSQLI_ASSOC);
        
                $select = $DB->query("SELECT * FROM approvedtable
            INNER JOIN categorytable ON approvedtable.cat_id = categorytable.cat_id
            INNER JOIN users ON approvedtable.userID = users.id
            INNER JOIN departmenttable ON users.dept_id = departmenttable.dept_id");
        
                $pdf->SetFont('Arial', 'B', 12);
                $pdf->Cell(0, 5, 'Purchase Request', 0, 1, 'C');
        
                $pdf->Ln(10);
        
                // Body content
        //cell(width, height, text, border, endline, [align]);
                $pdf->SetFont('Arial', '', 11);
                $pdf->Cell(30, 10, 'Entity Name:   ', 0, 0);
                $pdf->SetFont('Arial', 'B', 11);
                $pdf->Cell(90, 10, strtoupper('Central Philippines State University'), 0, 0);
                $pdf->Cell(100, 10, ucwords('fund cluster:'), 0, 1);
        
                $pdf->SetFont('Arial', '', 11);
        
                $view = $select->fetch_object();
                $pdf->Cell(30, 15, 'Office/Section', 1, 0);
                $content = ucwords($view->department);
                $pdf->Cell(90, 15, $content, 1, 0);
        
                $date = $view->created_at;
                $formatted_date = date('M, d, Y', strtotime($date));
                $pdf->Cell(30, 15, 'PR No.' . $view->request_id, 1, 0);
                $pdf->Cell(45, 15, 'Date: ' . $formatted_date, 1, 1);
        
                // define font size and style
                $pdf->Cell(30, 10, strtoupper('stock no.'), 1, 0);
                $pdf->Cell(15, 10, strtoupper('unit'), 1, 0);
                $pdf->Cell(75, 10, strtoupper('item description'), 1, 0);
                $pdf->Cell(15, 10, strtoupper('qty.'), 1, 0);
                $pdf->SetFont('Arial', '', 9);
                $pdf->Cell(20, 10, strtoupper('unit cost'), 1, 0);
                $pdf->SetFont('Arial', '', 12);
                $pdf->Cell(40, 10, strtoupper('total cost'), 1, 1);
// Retrieve the filtered data from the session
$filtered_data = $_SESSION['filtered_data'];
$id = 1;

$total_cost = 0;
if(!empty($filtered_data)){
    foreach ($filtered_data as $row) {
        $total_cost += $row['total_cost'];
        $pdf->Cell(30, 5, $id, 1, 0);
        $pdf->Cell(15, 5, ucwords($row['unit']), 1, 0);
        $pdf->SetFont('Arial', '', 8);
        $pdf->Cell(75, 5, ucwords($row['item_description']), 1, 0);
        $pdf->SetFont('Arial', '', 12);
        $pdf->Cell(15, 5, $row['quantity'], 1, 0);
        $pdf->Cell(20, 5, $row['cost'], 1, 0);
        $pdf->Cell(40, 5, $row['total_cost'], 1, 1);
        $id++;
    
        // Add a page break after 30 rows
        if ($id % 1 == 0) {
            if (count($filtered_data) < 20) {
                $num_blank_rows = 30 - count($filtered_data);
                for ($i = 0; $i < $num_blank_rows; $i++) {
                    $pdf->Cell(30, 5, '', 1, 0);
                    $pdf->Cell(15, 5, '', 1, 0);
                    $pdf->Cell(75, 5, '', 1, 0);
                    $pdf->Cell(15, 5, '', 1, 0);
                    $pdf->Cell(20, 5, '', 1, 0);
                    $pdf->Cell(40, 5, '', 1, 1);
                }
            }
            $pdf->AddPage();
        }
    }
}else{
$pdf->Cell(195, 10, ucwords('No data found!'), 1, 1, 'C');

}

// Count the total number of rows
// $num_rows = count($filtered_data);

// Add blank cells if the total number of rows is less than 20
// if ($num_rows < 20) {
//     $num_blank_rows = 100 - $num_rows;
//     for ($i = 0; $i < $num_blank_rows; $i++) {
//         $pdf->Cell(30, 5, '', 1, 0);
//         $pdf->Cell(15, 5, '', 1, 0);
//         $pdf->Cell(75, 5, '', 1, 0);
//         $pdf->Cell(15, 5, '', 1, 0);
//         $pdf->Cell(20, 5, '', 1, 0);
//         $pdf->Cell(40, 5, '', 1, 1);
//     }
// }

// bottom total
$pdf->Cell(155, 5, 'Total', 1, 0);
$pdf->Cell(40, 5, $total_cost, 1, 1);

$pdf->SetFont('Arial', '', 9);
// $pdf->MultiCell(195, 10, ucwords('purpose:   ' . $row['purpose']), 0, 'J');

        $pdf->Ln(20);
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Cell(20, 10, '', 0, 0);
        $pdf->Cell(90, 30, 'Requested by:', 0, 0);
        $pdf->Cell(45, 30, 'Approved by:', 0, 1);

        global $DB;
        $select = $DB->query("SELECT * FROM invoice");
        $designation = $select->fetch_object();

        $pdf->Cell(20, 10, '', 0, 0);
        $pdf->Cell(90, 10, strtoupper($designation->requestedfullname), 0, 0, 'C');
        $pdf->Cell(20, 10, '', 0, 0);
        $pdf->Cell(45, 10, strtoupper($designation->approvedfullname), 0, 1, 'C');

        $pdf->SetFont('Arial', '', 12);
        $pdf->Cell(20, 10, '', 0, 0);
        $pdf->Cell(90, 5, strtoupper($designation->requesteddesignation), 0, 0, 'C');
        $pdf->Cell(20, 10, '', 0, 0);
        $pdf->Cell(45, 5, strtoupper($designation->approveddesignation), 0, 1, 'C');

// Output PDF
$pdf->Output();